import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useCartStore } from '../store/useCartStore';
import { useOrderStore } from '../store/useOrderStore';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { PaymentMode, Order } from '../models';

export const Checkout: React.FC = () => {
  const { cartItems, cartSummary, clearCart } = useCartStore();
  const { placeOrder } = useOrderStore();
  const navigate = useNavigate();

  const [paymentMode, setPaymentMode] = useState<PaymentMode>('Online');
  const summary = cartSummary();

  const handlePlaceOrder = () => {
    const order: Order = {
      id: '', // generated by backend
      status: 'Pending',
      items: cartItems,
      summary: summary,
      address: { id: 'a1', type: 'Home', street: '123 Main St', city: 'Metropolis', state: 'NY', zip: '10001', isDefault: true },
      paymentMode: paymentMode,
      date: new Date()
    };

    placeOrder(order).then(() => {
      clearCart();
      navigate('/orders');
    }).catch(err => {
      console.error(err);
      // For mock purposes if it fails because backend isn't there, we just act like it worked.
      clearCart();
      navigate('/orders');
    });
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 min-h-[60vh]">
      <h1 className="text-3xl font-bold text-secondary mb-8">Checkout</h1>
      
      <div className="space-y-6">
        {/* Delivery Address */}
        <Card padding>
          <div className="flex items-center justify-between mb-4 border-b border-gray-100 pb-4">
            <h2 className="text-xl font-bold text-secondary flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6 text-primary"><path d="M11.47 3.84a.75.75 0 011.06 0l8.99 8.99a.75.75 0 11-1.06 1.06l-8.46-8.46-8.46 8.46a.75.75 0 11-1.06-1.06l8.99-8.99z" /><path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" /></svg>
              Delivery Address
            </h2>
            <button className="text-primary text-sm font-medium hover:underline">Change</button>
          </div>
          <div className="flex items-start gap-3">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-5 h-5 text-gray-400 mt-1"><path fillRule="evenodd" d="M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z" clipRule="evenodd" /></svg>
            <div>
              <h3 className="font-bold text-secondary">Home</h3>
              <p className="text-gray-500 text-sm mt-1">123 Main St, Apartment 4B<br/>Metropolis, NY 10001</p>
            </div>
          </div>
        </Card>

        {/* Payment Mode */}
        <Card padding>
          <h2 className="text-xl font-bold text-secondary mb-4 border-b border-gray-100 pb-4 flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6 text-primary"><path d="M12 7.5a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5z" /><path fillRule="evenodd" d="M1.5 4.875C1.5 3.839 2.34 3 3.375 3h17.25c1.035 0 1.875.84 1.875 1.875v9.75c0 1.036-.84 1.875-1.875 1.875H3.375A1.875 1.875 0 011.5 14.625v-9.75zM8.25 9.75a3.75 3.75 0 117.5 0 3.75 3.75 0 01-7.5 0zM18.75 9a.75.75 0 00-.75.75v.008c0 .414.336.75.75.75h.008a.75.75 0 00.75-.75V9.75a.75.75 0 00-.75-.75h-.008zM4.5 9.75A.75.75 0 015.25 9h.008a.75.75 0 01.75.75v.008a.75.75 0 01-.75.75H5.25a.75.75 0 01-.75-.75V9.75z" clipRule="evenodd" /><path d="M2.25 18a.75.75 0 000 1.5c5.4 0 10.63.722 15.6 2.075 1.19.324 2.4-.558 2.4-1.82V18.75a.75.75 0 00-.75-.75H2.25z" /></svg>
            Payment Method
          </h2>
          
          <div className="space-y-3">
            <label className={`flex items-center gap-3 p-3 border rounded-lg cursor-pointer transition-all ${paymentMode === 'Online' ? 'border-primary bg-orange-50' : ''}`}>
              <input type="radio" name="payment" checked={paymentMode === 'Online'} onChange={() => setPaymentMode('Online')} className="text-primary focus:ring-primary h-5 w-5" />
              <div className="flex-1">
                <span className="font-medium text-secondary">Credit / Debit Card / UPI</span>
              </div>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-5 h-5 text-gray-400"><path d="M4.5 3.75a3 3 0 00-3 3v.75h21v-.75a3 3 0 00-3-3h-15z" /><path fillRule="evenodd" d="M22.5 9.75h-21v7.5a3 3 0 003 3h15a3 3 0 003-3v-7.5zm-18 3.75a.75.75 0 01.75-.75h6a.75.75 0 010 1.5h-6a.75.75 0 01-.75-.75zm.75 2.25a.75.75 0 000 1.5h3a.75.75 0 000-1.5h-3z" clipRule="evenodd" /></svg>
            </label>
            
            <label className={`flex items-center gap-3 p-3 border rounded-lg cursor-pointer transition-all ${paymentMode === 'COD' ? 'border-primary bg-orange-50' : ''}`}>
              <input type="radio" name="payment" checked={paymentMode === 'COD'} onChange={() => setPaymentMode('COD')} className="text-primary focus:ring-primary h-5 w-5" />
              <div className="flex-1">
                <span className="font-medium text-secondary">Cash on Delivery</span>
              </div>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-5 h-5 text-gray-400"><path d="M10.464 8.746c.227-.18.497-.311.786-.394v2.795a2.252 2.252 0 01-.786-.393c-.394-.313-.546-.681-.546-1.004 0-.323.152-.691.546-1.004zM12.75 15.662v-2.824c.347.085.664.228.921.421.427.32.579.686.579.991 0 .305-.152.671-.579.991a2.534 2.534 0 01-.921.42z" /><path fillRule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zM12.75 6a.75.75 0 00-1.5 0v.816a3.836 3.836 0 00-1.72.756c-.712.566-1.112 1.35-1.112 2.178 0 .829.4 1.612 1.113 2.178.502.4 1.102.647 1.719.756v2.978a2.536 2.536 0 01-.921-.421l-.879-.66a.75.75 0 00-.9 1.2l.879.66c.533.4 1.169.645 1.821.75V18a.75.75 0 001.5 0v-.81a4.124 4.124 0 001.821-.749c.745-.559 1.179-1.344 1.179-2.191 0-.847-.434-1.632-1.179-2.191a4.122 4.122 0 00-1.821-.75V8.354c.29.082.559.213.786.393l.415.33a.75.75 0 00.933-1.175l-.415-.33a3.836 3.836 0 00-1.719-.755V6z" clipRule="evenodd" /></svg>
            </label>
          </div>
        </Card>

        {/* Place Order */}
        <div className="flex items-center justify-between bg-white p-4 rounded-xl shadow-sm border border-gray-100">
          <div>
            <div className="text-sm text-gray-500">Total to pay</div>
            <div className="text-2xl font-bold text-secondary">₹{summary.total.toFixed(2)}</div>
          </div>
          <Button variant="primary" className="px-8" onClick={handlePlaceOrder}>Place Order</Button>
        </div>
      </div>
    </div>
  );
};
